version: "3.8"
services:
  backend:
    image: "fatascode/springboot-react-fullstack:11.5.2021.11.16.11"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
